1 entries in records
Started running calling sequence 1
Executing: CALL click.usp_d_category();
Error executing stored procedure usp_d_category: (psycopg2.errors.UndefinedColumn) column s.category does not exist
LINE 13:     WHERE t.category   = s.category
                                  ^
HINT:  Perhaps you meant to reference the column "t.category".
QUERY:  UPDATE click.d_category t
    SET	
		categorykey				=   s.categorykey,
		category				=	s.category,
		subcategory				=	s.subcategory,
		createdatetime			=	s.createdatetime,
		etlactiveind            =	s.etlactiveind,
        etljobname              =	s.etljobname,
        envsourcecd             =	s.envsourcecd,
        datasourcecd            =	s.datasourcecd,
        etlupdateddatetime       =	NOW()
    FROM dwh.d_category s
    WHERE t.category			=	s.category
    AND	  t.subcategory			=	s.subcategory
CONTEXT:  PL/pgSQL function click.usp_d_category() line 5 at SQL statement

[SQL: CALL click.usp_d_category();]
(Background on this error at: https://sqlalche.me/e/20/f405)
Error occurred: 'Pandas' object has no attribute 'targettablename'
Traceback (most recent call last):
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\silvertogold\__main__.py", line 67, in <module>
    main(cli_args)
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\silvertogold\__main__.py", line 59, in main
    sp_caller.call_sp(row)
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\common_utils\timing.py", line 49, in wrapper
    if record.targettablename:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Pandas' object has no attribute 'targettablename'
